// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOPTsOwY3Sc_lrR_2LOEt6wlF3BSp60J0',
    appId: '1:831791724470:android:76b0112d93a7405231b317',
    messagingSenderId: '831791724470',
    projectId: 'another-second-chance',
    storageBucket: 'another-second-chance.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNa1PjUhw6xCsXaFoCtQUNLWEfx76BNJY',
    appId: '1:831791724470:ios:a126163bc9b85cb631b317',
    messagingSenderId: '831791724470',
    projectId: 'another-second-chance',
    storageBucket: 'another-second-chance.firebasestorage.app',
    iosBundleId: 'com.anothersecondchance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNa1PjUhw6xCsXaFoCtQUNLWEfx76BNJY',
    appId: '1:831791724470:ios:125b67dd6d78727f31b317',
    messagingSenderId: '831791724470',
    projectId: 'another-second-chance',
    storageBucket: 'another-second-chance.firebasestorage.app',
    iosBundleId: 'com.example.homelyhope',
  );
}
